# Generated by Django 3.1.7 on 2021-03-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('emotions', models.JSONField(verbose_name='emotions')),
                ('prediction', models.JSONField(verbose_name='prediction')),
                ('response', models.CharField(default='None', max_length=200, verbose_name='response')),
            ],
        ),
        migrations.CreateModel(
            name='UserKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('keywords', models.JSONField(verbose_name='keywords')),
                ('url', models.URLField(max_length=500, verbose_name='url')),
                ('prediction', models.BooleanField(default=False, verbose_name='prediction')),
                ('response', models.CharField(default='None', max_length=200, verbose_name='response')),
            ],
        ),
    ]
