# Generated by Django 3.1.7 on 2021-03-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='record date')),
                ('emotions', models.JSONField(verbose_name='emotions')),
            ],
        ),
        migrations.CreateModel(
            name='UserKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='record date')),
                ('keywords', models.JSONField(verbose_name='keywords')),
                ('url', models.URLField(max_length=500, verbose_name='url')),
            ],
        ),
    ]
