# Generated by Django 3.1.7 on 2021-03-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEmotions',
            new_name='UserEmotion',
        ),
        migrations.RenameModel(
            old_name='UserKeywords',
            new_name='UserKeyword',
        ),
    ]
