# Generated by Django 3.1.7 on 2021-03-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_auto_20210320_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremotion',
            name='timestamp',
            field=models.DateTimeField(verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='userkeyword',
            name='timestamp',
            field=models.DateTimeField(verbose_name='timestamp'),
        ),
    ]
