# Generated by Django 3.1.7 on 2021-03-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_auto_20210320_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremotion',
            name='prediction',
            field=models.JSONField(default='None', max_length=200, verbose_name='prediction'),
        ),
        migrations.AddField(
            model_name='useremotion',
            name='response',
            field=models.CharField(default='None', max_length=200, verbose_name='prediction'),
        ),
        migrations.AddField(
            model_name='userkeyword',
            name='prediction',
            field=models.BooleanField(default=False, verbose_name='prediction'),
        ),
        migrations.AddField(
            model_name='userkeyword',
            name='response',
            field=models.CharField(default='None', max_length=200, verbose_name='response'),
        ),
    ]
