# Generated by Django 3.1.7 on 2021-03-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0005_auto_20210321_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremotion',
            name='response',
            field=models.CharField(default='None', max_length=200, verbose_name='response'),
        ),
    ]
